[project]
name = "projet-semestre"
version = "0.1.0"
description = "ISC-302 Data Computation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.0.1",
    "jupyter>=1.1.1",
    "wandb>=0.23.0",
]
